[package]
name = "hft-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"
reqwest = { version = "0.13.1", features = ["json", "query"] }
tokio = { version = "1.49.0", features = ["full"] }
hmac = "0.12.1"
sha2 = "0.10.9"
hex = "0.4.3"
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5.15"